name: psyplot-presi
channels:
    - conda-forge
dependencies:
    - python=3.8
    - jupyter_contrib_nbextensions
    - psy-view
    - jupyter
    - rise
    - matplotlib>=3.3
    - cartopy>=0.18
    - ipython>=7.14
    - dask
    - pip
    # Required for jupyter-desktop-server
    - websockify
    - pip:
        - jupyter-desktop-server
